### ISSUE TITLE
Automatically create GitHub repository

### ISSUE THREAD

**Issue by nischayv** [hammer-io/tyr#26]
As a user, I would like a GitHub repository automatically generated for based on the project name from the CLI.

**Comment by nischayv** [comment]
https://www.sitepoint.com/javascript-command-line-interface-cli-node-js/

**Comment by jackcmeyer** [comment]
After #34 gets merged, we should be able to start working on this.

**Comment by NathanDeGraaf** [comment]
Some notes to myself about this topic:

We need to effectively have the following commands run.

git init
git add .
git commit -m "First commit"

curl -u 'USER' https://api.github.com/user/repos -d '{"name":"REPO"}'
git push https://USERNAME@github.com/NathanDeGraafTest/TestRepo1.git master
// This should prompt for password. otherwise use USERNAME:PASSWORD
